### PR TITLE
closes #4

### LINKED ISSUE #4: Add README
- what is the project for
- quickstart
...

### PR DESCRIPTION
**Pull request by RICK-FLORES**
closes #4

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Could you please add `closes #<Issue-number> ` to the description of your PR.
Github links your PR to the issue then 😄

**Comment by Cahllagerfeld** [comment]
> 
> 
> Happy to include more information if you'd like to share a little about the project.

You can have a look at [this](https://github.com/EddieHubCommunity/api) repo. We're planning to use Datastax Astra as our database. Unfortunately there's currently no Nest.js Module for that and documentation for the [existing](https://github.com/datastax/astrajs/tree/master/packages/collections)-Astra-Package is quite poor. Thats why we decided to build our own Nest-Module for the existing package. If this gets up and working its likely migrated to the EddieHubCommunity.

**Comment by RICK-FLORES** [comment]
Sure thing 😄 
closes #10

**Comment by Cahllagerfeld** [comment]
You need to adjust this in the description, not in a comment 😄
And you need to link the issue, for the Readme its `# 4`, not the PR 😄

**Comment by RICK-FLORES** [comment]
Haha. Whoops. Sorry still getting the hang of open source.

**Comment by RICK-FLORES** [comment]
Thanks for your patience. Haha. Hope I did this correctly. Please let me know.

**Comment by Cahllagerfeld** [comment]
You could leave the title as a little description on what the PR is about.
In your description you could add somethink like 
```md
closes #4 
Added Readme to Project
```
Link the PR to the issue and a short description what you did.

But I think this PR looks good for now 👍

**Comment by Cahllagerfeld** [comment]
What I didnt realize is that you merged ur PR to issue-6 of my Repo.
You could have opend it for merge into `main` of the repo.

**Pull request merged**
